// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHec0zlPc_SO3gFBDcNk-jdvMM71KQvCI',
    appId: '1:705554857478:web:1fd5094e65bf17f11d4d87',
    messagingSenderId: '705554857478',
    projectId: 'instaapp-c234b',
    authDomain: 'instaapp-c234b.firebaseapp.com',
    storageBucket: 'instaapp-c234b.appspot.com',
    measurementId: 'G-BJ5RS5Z3MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3XovFfj6WnEkELeAswJF4U6cGQhx8MYI',
    appId: '1:705554857478:android:a6726fc63a21c5091d4d87',
    messagingSenderId: '705554857478',
    projectId: 'instaapp-c234b',
    storageBucket: 'instaapp-c234b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2kqc7zw-3Ag3a_dXBpg3dyEBCbkhr-1g',
    appId: '1:705554857478:ios:ec762be0df3cb8961d4d87',
    messagingSenderId: '705554857478',
    projectId: 'instaapp-c234b',
    storageBucket: 'instaapp-c234b.appspot.com',
    iosBundleId: 'com.example.instaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2kqc7zw-3Ag3a_dXBpg3dyEBCbkhr-1g',
    appId: '1:705554857478:ios:ec762be0df3cb8961d4d87',
    messagingSenderId: '705554857478',
    projectId: 'instaapp-c234b',
    storageBucket: 'instaapp-c234b.appspot.com',
    iosBundleId: 'com.example.instaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHec0zlPc_SO3gFBDcNk-jdvMM71KQvCI',
    appId: '1:705554857478:web:0c4c44806701433e1d4d87',
    messagingSenderId: '705554857478',
    projectId: 'instaapp-c234b',
    authDomain: 'instaapp-c234b.firebaseapp.com',
    storageBucket: 'instaapp-c234b.appspot.com',
    measurementId: 'G-6EQ034TF5L',
  );
}
